### ISSUE TITLE
hypdoc's loading of hyperref leads to option clash

### ISSUE THREAD

**Issue by hmenke** [ho-tex/hypdoc#1]
Since https://github.com/latex3/latex2e/pull/492 the `doc` package from the LaTeX kernel which is used in `ltxdoc` unconditionally loads `hypdoc` in the `begindocument/before` hook.

Unfortunately `hypdoc` loads `hyperref` again but with a hardcoded set of options, so an option clash is essentially unavoidable.

The corresponding issue on the LaTeX bug tracker was closed (https://github.com/latex3/latex2e/issues/822), just mentioning a couple of workarounds, which all require modifications to the preamble that are not at all obvious in my opinion.

#### Minimal working example

```latex
\documentclass{ltxdoc}
\usepackage{hyperref}
\begin{document}
\end{document}
```

```
! LaTeX Error: Option clash for package hyperref.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.54 ]{hyperref}[2002/05/09]
                            %
?
```

#### Proposed fix

I'm proposing to not reload `hyperref` if it is detected that it is loaded and instead use the late options selection using `\hypersetup` for all parameters.

```patch
diff --git a/hypdoc.dtx b/hypdoc.dtx
index 91fef65..69c51e4 100644
--- a/hypdoc.dtx
+++ b/hypdoc.dtx
@@ -375,13 +375,12 @@ and the derived files
 \fi
 %    \end{macrocode}
 %    \begin{macrocode}
-\RequirePackage[%
+\@ifpackageloaded{hyperref}{}{\RequirePackage{hyperref}[2002/05/09]}
+\hypersetup{%
   hyperindex=false,%
   pdfusetitle,%
   colorlinks,%
-  pdfpagelabels%
-]{hyperref}[2002/05/09]%
-\hypersetup{%
+  pdfpagelabels,%
   plainpages=false,%
   bookmarksopen,%
   bookmarksnumbered,%
```

**Comment by u-fischer** [comment]
It is not possible to set ` hyperindex`, `pdfusetitle` and `pdfpagelabels` in `\hypersetup`. These are package only options. But apart from this, I think adding a test is not a bad idea.

**Comment by u-fischer** [comment]
I updated hypdoc and sent it to ctan.
