### ISSUE TITLE
Active ^^M is redefined to empty at begindocument

### ISSUE THREAD

**Issue by muzimuzhi** [ho-tex/hypdoc#3]
Active `^^M` is let to `\par` in latex kernel, but `hypdoc` redefines it to an empty macro at begindocument, `\HD@savedest@init`. Since now `doc` v3 loads `hypdoc` by default, any use cases that depend on the default `\let^^M\par` will fail, for example pgf-tikz/pgf#1171.

It seems the setting `\def^^M{}` is for inputting `\jobname.hd`, so perhaps it's save to revert it afterwards.

```tex
\documentclass{article}

\begingroup \catcode`\^^M=13 \show^^M \fail\endgroup % > ^^M=\par.
\usepackage{hypdoc}
\begingroup \catcode`\^^M=13 \show^^M \fail\endgroup % > ^^M=\par.

\begin{document}
\begingroup \catcode`\^^M=13 \show^^M \fail\endgroup % > ^^M=macro:<NEWLINE>->.
\end{document}
```

`\def^^M{}` appears on line 752:
https://github.com/ho-tex/hypdoc/blob/ab7d4705a70a122126e4b6786bcc1342de794cd2/hypdoc.dtx#L734-L764

**Comment by davidcarlisle** [comment]
the package doesn't document that change so reverting after the input looks correct to me. @u-fischer ?

**Comment by u-fischer** [comment]
@davidcarlisle  I see no reason why it shouldn't do the same it does for `~`. But this here errors too, so perhaps the datavisualization code needs to guard itself against `^^M` changes better too:

~~~~
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{datavisualization}

\begin{document}
\obeylines
\tikz \datavisualization data group {points} = {
  data {
    x, y
    0, 1
    1, 2
    2, 2
    5, 1
    2, 0
    1, 1
  }
};

\end{document}
~~~~

**Comment by davidcarlisle** [comment]
we don't seem to have any test files here, but the example in https://github.com/pgf-tikz/pgf/issues/1171 works without error after the last commit

**Comment by muzimuzhi** [comment]
> But this here errors too, so perhaps the datavisualization code needs to guard itself against `^^M` changes better too:

@u-fischer Thanks for the new test case. Actually the example in pgf-tikz/pgf#1171 is more relevant to `codexample`, an environment only used in typesetting `pgfmanual`, than datavisualization. I've added some explanations in https://github.com/pgf-tikz/pgf/issues/1171#issuecomment-1173220216.

**Comment by davidcarlisle** [comment]
v1.17 fixing this is at ctan
