### ISSUE TITLE
Regression: hypdoc makes bibliography formatting fail in TeXLlive 2022

### ISSUE THREAD

**Issue by msdemlei** [ho-tex/hypdoc#6]
The document at https://github.com/ivoa-std/VOUnits (use make to build it) formats nicely in TeXLive earlier than 2022.  However, with TeXLive 2022 at least on MacOS, the build fails with

```
Runaway argument?
\parindent \z@ \bibpreamble \bibfont \list {\@biblabel {\the \c@NAT@ctr \ETC.
! Paragraph ended before \HD@@guesstoclevel was complete.
<to be read again> 
\par 
l.1 \begin{thebibliography}
                         {xx}
```

when including the bibliography (bug report: https://github.com/ivoa-std/ivoatex/issues/97 reported by @nxg).  I observe that in earlier versions, the file hypdoc is not even included by TeX (at least according to the log file).

I have poked around a bit in the log of the failing run (https://github.com/ivoa-std/ivoatex/files/10466944/VOUnits.log) but was somewhat frustrated because I could not even figure out what exactly loads hypdoc apparently at begin{document} time.

Can someone here shed some light on why hypdoc is included in TeXLive 2022 when it was not before – and perhaps how we can work around the problem?

**Comment by u-fischer** [comment]
oh well, natbib adds a \par to the definition, but the definition in hypdoc that tries to detect the toclevel is not long

~~~~
\documentclass{article}

\usepackage[numbers]{natbib}
\usepackage{hypdoc}
\makeatletter
\long\def\HD@@guesstoclevel#1#2\HD@end{%
  \@ifundefined{toclevel@\expandafter\@gobble\string#1\@empty}{%
    1%
  }{%
    \@nameuse{toclevel@\expandafter\@gobble\string#1\@empty}%
  }%
}

\begin{document}
blub
\begin{thebibliography}{99}
\bibitem{yyyy}
xxxx
\end{thebibliography}
\end{document}
~~~~
