### ISSUE TITLE
Wrong git tag name "v1.9-2023-10-26" for release 1.19

### ISSUE THREAD

**Issue by muzimuzhi** [ho-tex/hypdoc#8]
It is indeed [v1.19](https://github.com/ho-tex/hypdoc/commit/f64930f0d4cee3e7322e6a12bf69e24772e9600f), but the corresponding git tag was named "v1.9-2023-10-26".

See https://github.com/ho-tex/hypdoc/releases/tag/v1.9-2023-10-26.

**Comment by u-fischer** [comment]
oh well ;-). My numbers (and dates) do have a probability > 0 to be wrong.

**Comment by u-fischer** [comment]
I think I repaired  that.

**Comment by muzimuzhi** [comment]
Thanks! 😄
